# Generated by Django 3.1.5 on 2021-01-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.IntegerField(max_length=3, verbose_name='Idade')),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('apelido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apelido')),
                ('observacao', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observação')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
