# Generated by Django 3.1.5 on 2021-01-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210108_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(verbose_name='Idade'),
        ),
    ]
